#ifndef __REVISION_SQL_H__
#define __REVISION_SQL_H__
#define REVISION_DB_CHARACTERS "required_0028_xxxxx_01_characters_character_phase_data"
#define REVISION_DB_MANGOS "required_0034_xxxxx_03_mangos_player_classlevelstats"
#define REVISION_DB_REALMD "required_0014_xxxxx_01_realmd_account_access"
#endif // __REVISION_SQL_H__
