#ifndef __REVISION_SQL_H__
#define __REVISION_SQL_H__
#define REVISION_DB_CHARACTERS "required_0028_xxxxx_01_characters_character_phase_data"
#define REVISION_DB_MANGOS "required_0046_xxxxx_01_mangos_player_xp_for_level"
#define REVISION_DB_REALMD "required_0014_xxxxx_01_realmd_account_access"
#endif // __REVISION_SQL_H__
