
// -*- C++ -*-
// $Id: Version.h 91613 2010-09-04 09:31:47Z johnnyw $
// This is file was automatically generated by \$ACE_ROOT/bin/make_release.

#define ACE_MAJOR_VERSION 5
#define ACE_MINOR_VERSION 8
#define ACE_BETA_VERSION 2
#define ACE_VERSION "5.8.2"
